apiVersion: v1
kind: Secret
metadata:
  #the name of the secret
  name: mongodb-secret
  #indicates a key value pair
type: Opaque
data:
  #base 63 encoded username and password
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
